### ISSUE TITLE
Change IP address is APIClient.java

### ISSUE THREAD

**Issue by ghost** [cbreuner/hackathon#2]
I'm guessing you had a Digitalocean VM running your backend, which you've since taken down.

The problem was that it that IP ended up being recycled for one of my VMs. It looks like someone ran the app because my server was getting a bunch of hits (multiple times a second), for sendInvites.php. I've since changed the IP on my server.  

I suggest you change the IP referenced in the code on this line:

`private static final String BASE_URL = "http://107.170.231.224";`

to be something else so the app doesn't inadvertently end up spamming the next person.

**Comment by TobbenTM** [comment]
Huh, that's unfortunate. The thing is, this app isn't really published anywhere, and only a handful of people are running the app. Maybe @cbreuner could check with them? :)

**Comment by ghost** [comment]
I noticed over the weekend that my server was getting hit from 198.189.249.64. Which appears to be located in Salinas, CA.  http://www.ip-tracker.org/locator/ip-lookup.php?ip=198.189.249.64

It started around 1:15 pm on 2/20 and went on until 11:15 pm on 2/21. Towards the end it was multiple times a second.

Also, it always was referencing the same FBID:

```
198.189.249.64 - - [20/Feb/2016:13:13:41 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:15:41 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:16:45 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:17:41 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:18:45 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:19:41 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:20:45 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
198.189.249.64 - - [20/Feb/2016:13:21:41 -0500] "GET /showInvites.php?FBID=1043449529010695 HTTP/1.1" 404 5666 "-" "-"
```

**Comment by cbreuner** [comment]
I think Fatema must have found a developer to work with them... I've texted her to let her know as I think they opened up their own repo somewhere. Thank you for letting me know. 

Sent via the Samsung Galaxy Note® Edge, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by cbreuner** [comment]
Removed and pushed. Thanks @cshipley
